"""Tests for workspace generator module."""

from pathlib import Path

import pytest

from cli.generator import generate_workspace
from cli.questionnaire import WorkspaceConfig


@pytest.fixture
def mock_config() -> WorkspaceConfig:
    """Return a mock workspace config."""
    return WorkspaceConfig(
        emacs_style="minimal",
        profile="python-general",
        ai_provider="claude",
        os_name="macos",
        python_version="3.12.0",
        emacs_path="/usr/local/bin/emacs",
        emacs_version="29.1",
    )


def test_generate_workspace_creates_files(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Verify that generate_workspace emits the correctly named files."""
    dest_dir = tmp_path / ".emaw"
    
    generate_workspace(mock_config, dest_dir)
    
    assert dest_dir.is_dir()
    assert (dest_dir / "early-init.el").is_file()
    assert (dest_dir / "init.el").is_file()


def test_generate_workspace_content(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Verify that templates render dynamic choices properly."""
    dest_dir = tmp_path / ".emaw"
    
    generate_workspace(mock_config, dest_dir)
    
    early_init_text = (dest_dir / "early-init.el").read_text()
    assert "auto-generated by emaw" in early_init_text.lower()
    assert "minimal style optimizations applied" in early_init_text.lower()
    
    init_text = (dest_dir / "init.el").read_text()
    assert "Profile: python-general" in init_text
    assert "AI Provider: claude" in init_text
    # Check packages from resolved profile
    assert "(use-package corfu)" in init_text
    assert "(use-package python-mode)" in init_text
    # Check AI adapter conditional
    assert "Configured AI Adapter: claude" in init_text
