"""Tests for workspace generator module."""

from pathlib import Path

import pytest

from cli.generator import generate_workspace
from cli.questionnaire import WorkspaceConfig


@pytest.fixture
def mock_config() -> WorkspaceConfig:
    """Return a mock workspace config for the claude provider."""
    return WorkspaceConfig(
        emacs_style="minimal",
        profile="python-general",
        ai_provider="claude",
        os_name="macos",
        python_version="3.12.0",
        emacs_path="/usr/local/bin/emacs",
        emacs_version="29.1",
    )


@pytest.fixture
def ollama_config() -> WorkspaceConfig:
    """Return a mock workspace config for the ollama provider."""
    return WorkspaceConfig(
        emacs_style="minimal",
        profile="local-ollama",
        ai_provider="ollama",
        os_name="linux",
        python_version="3.12.0",
        emacs_path="/usr/bin/emacs",
        emacs_version="29.4",
    )


@pytest.fixture
def no_ai_config() -> WorkspaceConfig:
    """Return a mock workspace config with no AI provider."""
    return WorkspaceConfig(
        emacs_style="minimal",
        profile="python-general",
        ai_provider="none",
        os_name="macos",
        python_version="3.12.0",
        emacs_path="/usr/local/bin/emacs",
        emacs_version="29.1",
    )


def test_generate_workspace_creates_files(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Verify that generate_workspace emits the correctly named files."""
    dest_dir = tmp_path / ".emaw"

    generate_workspace(mock_config, dest_dir)

    assert dest_dir.is_dir()
    assert (dest_dir / "early-init.el").is_file()
    assert (dest_dir / "init.el").is_file()
    assert (dest_dir / "emaw-mode.el").is_file()
    assert (dest_dir / "tasks.json").is_file()


def test_generate_workspace_content(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Verify that templates render dynamic choices properly."""
    dest_dir = tmp_path / ".emaw"

    generate_workspace(mock_config, dest_dir)

    early_init_text = (dest_dir / "early-init.el").read_text()
    assert "auto-generated by emaw" in early_init_text.lower()
    assert "minimal style optimizations applied" in early_init_text.lower()

    init_text = (dest_dir / "init.el").read_text()
    assert "Profile: python-general" in init_text
    assert "AI Provider: claude" in init_text
    # Check packages from resolved profile
    assert "(use-package corfu)" in init_text
    assert "(use-package python-mode)" in init_text
    # init.el now loads the adapter file rather than printing a message
    assert "claude-adapter.el" in init_text


# ---------------------------------------------------------------------------
# Story 3.1 – AI Adapter file generation
# ---------------------------------------------------------------------------


def test_generate_claude_adapter_creates_file(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """claude adapter file is created when ai_provider is claude."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)
    assert (dest_dir / "claude-adapter.el").is_file()


def test_generate_ollama_adapter_creates_file(
    ollama_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """ollama adapter file is created when ai_provider is ollama."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(ollama_config, dest_dir)
    assert (dest_dir / "ollama-adapter.el").is_file()


def test_no_adapter_file_when_provider_is_none(
    no_ai_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """No adapter .el file is created when ai_provider is none."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(no_ai_config, dest_dir)
    assert not (dest_dir / "claude-adapter.el").exists()
    assert not (dest_dir / "ollama-adapter.el").exists()


def test_claude_adapter_content(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Generated claude-adapter.el contains required packages and keybindings."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)

    text = (dest_dir / "claude-adapter.el").read_text()
    assert "(use-package vterm" in text
    assert "(use-package claude-code" in text
    assert 'C-c C-a' in text
    assert "#'claude-code" in text
    assert "#'claude-code-send-region" in text
    assert "#'claude-code-send-buffer" in text


def test_ollama_adapter_content(
    ollama_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Generated ollama-adapter.el contains gptel config and keybindings."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(ollama_config, dest_dir)

    text = (dest_dir / "ollama-adapter.el").read_text()
    assert "(use-package gptel" in text
    assert "gptel-make-ollama" in text
    assert "localhost:11434" in text
    assert 'C-c C-a' in text
    assert "#'gptel-send" in text
    assert "#'gptel-rewrite" in text


def test_init_el_loads_claude_adapter(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """init.el contains a load-file call referencing claude-adapter.el."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)

    init_text = (dest_dir / "init.el").read_text()
    assert "claude-adapter.el" in init_text
    assert "load-file" in init_text


# ---------------------------------------------------------------------------
# Story 4.1 – Emacs Minor Mode Integration
# ---------------------------------------------------------------------------


def test_init_el_loads_emaw_mode(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """init.el contains code to load and hook emaw-mode.el."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)

    init_text = (dest_dir / "init.el").read_text()
    assert "emaw-mode.el" in init_text
    assert "prog-mode-hook" in init_text


def test_emaw_mode_content(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """Generated emaw-mode.el contains the necessary interactive commands and map."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)

    text = (dest_dir / "emaw-mode.el").read_text()
    assert "(defun emaw-doctor ()" in text
    assert "(defun emaw-init ()" in text
    assert "(defun emaw-sync ()" in text
    assert "(async-shell-command \"emaw doctor\"" in text
    assert "(async-shell-command \"emaw init\"" in text
    assert "(async-shell-command \"emaw sync\"" in text
    assert "(define-minor-mode emaw-mode" in text
    assert "C-c C-e d" in text
    assert "C-c C-e i" in text
    assert "C-c C-e s" in text
    assert "(defun emaw-task-run-tests ()" in text
    assert "(defun emaw-task-format-code ()" in text
    # Tasks now delegate to emaw--run-task, not async-shell-command directly
    assert "(emaw--run-task \"run-tests\")" in text
    assert "(defun emaw--run-task" in text
    assert "(defun emaw--task-sentinel" in text
    assert "emaw--last-task-status" in text
    assert "locate-dominating-file default-directory \".emaw\"" in text
    assert "C-c C-e t 1" in text
    assert "#'emaw-task-run-tests" in text


def test_generate_tasks_json_content(
    mock_config: WorkspaceConfig, tmp_path: Path
) -> None:
    """tasks.json maps labels to shell execution commands."""
    dest_dir = tmp_path / ".emaw"
    generate_workspace(mock_config, dest_dir)

    import json
    tasks = json.loads((dest_dir / "tasks.json").read_text())
    assert tasks["run-tests"] == "pytest"
    assert tasks["format-code"] == "black ."
    assert tasks["lint-code"] == "ruff check ."
